service: ai-endeavour-svc
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  timeout: 10
  stage: dev
  region: ap-south-1
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource: "arn:aws:s3:::aiendeavour/*"

environment:
    BUCKET_NAME: aiendeavour

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDonwloadCache: true
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  upload:
    handler: handler.upload
    events:
      - http:
          path: upload
          method: post
          cors: true

  train:
    handler: handler.train
    events:
      - http:
          path: train
          method: post
          cors: true

  predict:
    handler: handler.predict
    events:
      - http:
          path: predict
          method: post
          cors: true

plugins:
  - serverless-python-requirements