service: neuralstyletransfer

provider:
    name: aws
    runtime: python3.8
    stage: dev
    region: ap-south-1
    timeout: 60

    environment:
        MODEL_BUCKET_NAME: eva4p2bucket1
        MODEL_FILE_NAME_KEY: model-nst.pt
    iamRoleStatements:
        - Effect: "Allow"
          Action:
            - s3:getObject
          Resource: arn:aws:s3:::eva4p2bucket1/*
custom:
    pythonRequirements:
        dockerizePip: true
        zip: true
        slim: true
        strip: false
        noDeploy:
            - docutils
            - jmespath
            - pip
            - python-dateutil
            - setuptools
            - six
            - tensorboard
        useStaticCache: true
        useDonwloadCache: true
        cacheLocation: "./cache"
        
package:
    individually: false
    exclude:
        - package.json
        - package-log.json
        - node_modules/**
        - cache/**
        - test/**
        - __pycache__/**
        - .pytest_cache/**
        - model/**
        
functions:
    main_handler:
        handler: handler.getneuralstyletransfer
        memorySize: 3008
        timeout: 60
        events:
            - http:
                path: nst
                method: post
                cors: true

plugins:
  - serverless-python-requirements
