service: image-caption

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-south-1
  timeout: 60
  environment:
    S3_BUCKET: eva4p2bucket1
    MODEL_PATH: model-caption.pth.tar
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::eva4p2bucket1/*

functions:
  imagecaption:
    handler: handler.generatecaption
    memorySize: 3008
    timeout: 60
    events:
      - http:
          path: caption
          method: post
          cors: true
plugins:
  - serverless-python-requirements
